export const Works = [
  {
    id: "1",
    onAir: "방영 중",
    title: "더 글로리",
    actors: "송혜교, 이도현 외",
    producer: "안길호, 김은숙",
  },
  {
    id: "2",
    onAir: "방영 중",
    title: "환혼: 빛과 그림자",
    actors: "이재욱, 고윤정 외",
    producer: "박준화, 배현진",
  },
  {
    id: "3",
    onAir: "방영 중",
    title: "슈룹",
    actors: "김혜수, 김해숙 외",
    producer: "김형식",
  },
  {
    id: "4",
    onAir: "종영작",
    title: "스물다섯 스물하나",
    actors: "김태리, 남주혁 외",
    producer: "김선태, 김범래",
  },
  {
    id: "5",
    onAir: "종영작",
    title: "고스트 닥터",
    actors: "김범, 정지훈 외",
    producer: "문석환, 오광희",
  },
  {
    id: "6",
    onAir: "종영작",
    title: "배드앤크레이지",
    actors: "이동욱, 위하준 외",
    producer: "유선동",
  },
  {
    id: "7",
    onAir: "종영작",
    title: "호텔 델루나",
    actors: "이지은, 여진구 외",
    producer: "오충환, 김정현",
  },
  {
    id: "8",
    onAir: "종영작",
    title: "사랑의 불시착",
    actors: "현빈, 손예진 외",
    producer: "이정효, 김희원, 김나영",
  },
  {
    id: "9",
    onAir: "종영작",
    title: "미스터 선샤인",
    actors: "이병헌, 김태리 외",
    producer: "이응복",
  },
  {
    id: "10",
    onAir: "종영작",
    title: "비밀의 숲",
    actors: "조승우, 배두나 외",
    producer: "안길호, 유제원",
  },
  {
    id: "11",
    onAir: "종영작",
    title: "도깨비",
    actors: "공유, 김고은 외",
    producer: "이응복, 윤종호, 권혁찬",
  },
  {
    id: "12",
    onAir: "종영작",
    title: "시그널",
    actors: "이제훈, 김혜수, 조진웅",
    producer: "김원석",
  },
  {
    id: "13",
    onAir: "종영작",
    title: "미생",
    actors: "임시완, 이성민, 강소라 외",
    producer: "김원석",
  },
  {
    id: "14",
    onAir: "종영작",
    title: "드림하이",
    actors: "배수지, 김수현 외",
    producer: "이응복, 김성윤",
  },
];
