export const category = [
  {
    id: "1",
    type: "new",
    explain: "당신의 꿈의 실현을 스튜디오 드래곤에서 시작하세요.",
    num: "1",
  },
  {
    id: "2",
    type: "career",
    explain: "자사와 새로운 도전을 함께할 당신을 찾습니다.",
    num: "2",
  },
  {
    id: "3",
    type: "intern",
    explain: "스튜디오 드래곤에서 나의 내일을 만들 인턴을 모집합니다.",
    num: "0",
  },
];

export const recruitList = [
  {
    id: 1,
    type: "new",
    title: "드라마 제작관리 신입 채용",
    deadLine: 10,
    start: "2022.12.28",
  },
  {
    id: 2,
    type: "new",
    title: "드라마 제작관리 신입 채용",
    deadLine: "마감",
    start: "2022.11.28",
  },
  {
    id: 3,
    type: "new",
    title: "드라마 제작관리 신입 채용",
    deadLine: "마감",
    start: "2022.10.28",
  },
  {
    id: 4,
    type: "new",
    title: "드라마 제작관리 신입 채용",
    deadLine: "마감",
    start: "2022.8.28",
  },
  {
    id: 5,
    type: "career",
    title: "드라마 제작관리 경력 채용",
    deadLine: 15,
    start: "2022.12.23",
  },
  {
    id: 6,
    type: "career",
    title: "법무 경력 채용",
    deadLine: 8,
    start: "2022.12.16",
  },
  {
    id: 7,
    type: "career",
    title: "드라마 제작관리 경력 채용",
    deadLine: "마감",
    start: "2022.10.18",
  },
  {
    id: 8,
    type: "career",
    title: "드라마 협찬 마케팅 경력사원 채용",
    deadLine: "마감",
    start: "2022.10.16",
  },
  {
    id: 9,
    type: "intern",
    title: "그래픽 디자인 인턴 채용",
    deadLine: "마감",
    start: "2022.12.10",
  },
  {
    id: 10,
    type: "intern",
    title: "디지털 콘텐츠 기획/제작 인턴 채용",
    deadLine: "마감",
    start: "2022.12.10",
  },
  {
    id: 11,
    type: "intern",
    title: "드라마 제작관리 인턴 채용",
    deadLine: "마감",
    start: "2022.11.15",
  },
  {
    id: 12,
    type: "intern",
    title: "현장 체험형 인턴 채용",
    deadLine: "마감",
    start: "2022.11.15",
  },
];
